plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.ai.agentpro'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ai.agentpro'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
        buildConfigField 'String', 'BUILD_TAG', '"node-action"'
        buildConfigField 'String', 'BUILD_CHANNEL', '"x83c-a"'
        buildConfigField 'int', 'BUILD_SEQ', '306'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
}
